import { useCallback, useEffect, useRef, useState } from 'react'
import { FilePlus2, LogOut, Share2, Trash2 } from 'lucide-react'
import type { Session } from '@supabase/supabase-js'
import { Auth } from './components/Auth'
import { DocumentList } from './components/DocumentList'
import { DocumentTabs } from './components/DocumentTabs'
import { Editor } from './components/Editor'
import { FileUploader } from './components/FileUploader'
import { ShareModal } from './components/ShareModal'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import type { Document, SaveState } from './types'

function App() {
  const [session, setSession] = useState<Session | null>(null); const [documents, setDocuments] = useState<Document[]>([]); const [openDocumentIds, setOpenDocumentIds] = useState<string[]>([]); const [selected, setSelected] = useState<Document | null>(null); const [loading, setLoading] = useState(true); const [deleting, setDeleting] = useState(false); const [error, setError] = useState(''); const [saveState, setSaveState] = useState<SaveState>('idle'); const [shareOpen, setShareOpen] = useState(false); const saveTimer = useRef<number | undefined>(undefined)
  useEffect(() => { if (!isSupabaseConfigured) { setLoading(false); return }; supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false) }); const { data: listener } = supabase.auth.onAuthStateChange((_event, nextSession) => setSession(nextSession)); return () => listener.subscription.unsubscribe() }, [])
  useEffect(() => { if (!session) { setDocuments([]); setOpenDocumentIds([]); setSelected(null); return }; setLoading(true); supabase.from('documents').select('*').order('updated_at', { ascending: false }).then(({ data, error: fetchError }) => { if (fetchError) setError(fetchError.message); else setDocuments((data ?? []) as Document[]); setLoading(false) }) }, [session])
  const openDocument = (document: Document) => { setOpenDocumentIds((current) => current.includes(document.id) ? current : [...current, document.id]); setSelected(document); setSaveState('idle') }
  const closeDocument = (documentId: string) => { setOpenDocumentIds((current) => { const remaining = current.filter((id) => id !== documentId); if (selected?.id === documentId) { const nextId = remaining[remaining.length - 1]; setSelected(documents.find((document) => document.id === nextId) ?? null); setSaveState('idle') }; return remaining }) }
  const createDocument = async () => { if (!session) return; setError(''); const { data, error: createError } = await supabase.from('documents').insert({ title: 'Untitled document', content: '<p></p>', owner_id: session.user.id }).select().single(); if (createError) { setError(createError.message); return }; setDocuments((current) => [data as Document, ...current]); openDocument(data as Document) }
  const saveDocument = useCallback((content: string) => { if (!selected) return; const documentId = selected.id; window.clearTimeout(saveTimer.current); setSaveState('saving'); saveTimer.current = window.setTimeout(async () => { try { if (!navigator.onLine) throw new TypeError('Offline'); const { error: saveError } = await supabase.from('documents').update({ content }).eq('id', documentId); if (saveError) throw saveError; localStorage.removeItem(`paperwork:offline:${documentId}`); setSaveState('saved'); setDocuments((current) => current.map((document) => document.id === documentId ? { ...document, content } : document)) } catch (saveError) { const message = saveError instanceof Error ? saveError.message : 'Could not save document.'; if (!navigator.onLine || /network|fetch|offline/i.test(message)) { localStorage.setItem(`paperwork:offline:${documentId}`, content); setSaveState('offline') } else { setSaveState('idle'); setError(message) } } }, 800) }, [selected])
  useEffect(() => () => window.clearTimeout(saveTimer.current), [])
  const deleteDocument = async () => { if (!selected || !window.confirm(`Delete "${selected.title}"? This cannot be undone.`)) return; setDeleting(true); setError(''); const deletedId = selected.id; const { error: deleteError } = await supabase.from('documents').delete().eq('id', deletedId); if (deleteError) { setError(deleteError.message); setDeleting(false); return }; setDocuments((current) => current.filter((document) => document.id !== deletedId)); closeDocument(deletedId); setDeleting(false) }
  if (loading) return <main className="grid min-h-screen place-items-center text-sm text-stone-600">Loading workspace...</main>
  if (!session) return <Auth />
  const openDocuments = documents.filter((document) => openDocumentIds.includes(document.id))
  return <main className="min-h-screen bg-[#f7f6f0] p-4 text-[#1d2723] sm:p-8"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[280px_1fr]"><aside className="rounded-lg border border-stone-200 bg-white p-4 shadow-sm"><div className="mb-7 flex items-center justify-between"><span className="font-sans text-lg font-bold tracking-wide">Paperwork</span><button title="New document" onClick={createDocument} className="rounded border border-emerald-700 p-2 text-emerald-800 hover:bg-emerald-50"><FilePlus2 size={18} /></button></div><DocumentList documents={documents} currentUserId={session.user.id} selectedId={selected?.id} onSelect={openDocument} /><button onClick={() => supabase.auth.signOut()} className="mt-6 flex items-center gap-2 font-sans text-sm text-stone-500 hover:text-stone-900"><LogOut size={15} /> Sign out</button></aside><section className="min-w-0"><DocumentTabs documents={openDocuments} selectedId={selected?.id} onSelect={openDocument} onClose={closeDocument} /><header className="mb-4 flex items-center justify-between gap-3"><div><p className="font-sans text-xs font-semibold uppercase tracking-[.14em] text-emerald-800">Collaborative editor</p><h1 className="mt-1 text-2xl font-bold">{selected?.title ?? 'Document dashboard'}</h1></div>{selected?.owner_id === session.user.id && <div className="flex items-center gap-2"><button onClick={() => setShareOpen(true)} className="flex items-center gap-2 rounded bg-emerald-800 px-3 py-2 font-sans text-sm font-semibold text-white hover:bg-emerald-900"><Share2 size={16} /> Share</button><button title="Delete document" disabled={deleting} onClick={deleteDocument} className="rounded border border-red-200 p-2 text-red-700 hover:bg-red-50 disabled:opacity-50"><Trash2 size={18} /></button></div>}</header>{error && <p role="alert" className="mb-3 rounded border border-red-200 bg-red-50 p-3 font-sans text-sm text-red-800">{error}</p>}{selected ? <div className="rounded-lg border border-stone-200 bg-white p-5 shadow-sm sm:p-8"><Editor documentId={selected.id} content={String(selected.content ?? '')} saveState={saveState} onChange={saveDocument} /><FileUploader editorId={selected.id} onError={setError} /></div> : <div className="rounded-lg border border-dashed border-stone-300 bg-white p-12 text-center shadow-sm"><p className="text-xl font-bold">No documents open</p><p className="mt-2 font-sans text-sm text-stone-600">Select a document from the sidebar or create a new one to begin.</p></div>}</section></div>{selected && <ShareModal open={shareOpen} documentId={selected.id} onClose={() => setShareOpen(false)} />}</main>
}
export default App