create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null unique);
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, email) values (new.id, new.email); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table public.documents (id uuid primary key default gen_random_uuid(), title text not null default 'Untitled document', content jsonb not null default '"<p></p>"'::jsonb, owner_id uuid not null references public.profiles(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.document_access (document_id uuid not null references public.documents(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, primary key (document_id, user_id));
create function public.set_document_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger set_documents_updated_at before update on public.documents for each row execute procedure public.set_document_updated_at();
create function public.prevent_document_owner_change() returns trigger language plpgsql as $$ begin if new.owner_id <> old.owner_id then raise exception 'Document ownership cannot be changed'; end if; return new; end; $$;
create trigger prevent_document_owner_change before update on public.documents for each row execute procedure public.prevent_document_owner_change();
alter table public.profiles enable row level security; alter table public.documents enable row level security; alter table public.document_access enable row level security;
create policy "profiles readable by signed-in users" on public.profiles for select to authenticated using (true);
create function public.can_access_document(target_document_id uuid) returns boolean language sql security definer set search_path = public stable as $$ select exists (select 1 from public.document_access where document_id = target_document_id and user_id = auth.uid()) $$;
create function public.owns_document(target_document_id uuid) returns boolean language sql security definer set search_path = public stable as $$ select exists (select 1 from public.documents where id = target_document_id and owner_id = auth.uid()) $$;
create policy "owners and collaborators read documents" on public.documents for select to authenticated using (owner_id = auth.uid() or public.can_access_document(id));
create policy "users create owned documents" on public.documents for insert to authenticated with check (owner_id = auth.uid());
create policy "owners and collaborators edit documents" on public.documents for update to authenticated using (owner_id = auth.uid() or public.can_access_document(id)) with check (owner_id = auth.uid() or public.can_access_document(id));
create policy "owners delete documents" on public.documents for delete to authenticated using (owner_id = auth.uid());
create policy "owners view sharing" on public.document_access for select to authenticated using (public.owns_document(document_id));
create policy "owners manage sharing" on public.document_access for insert to authenticated with check (public.owns_document(document_id));
create policy "owners update sharing" on public.document_access for update to authenticated using (public.owns_document(document_id)) with check (public.owns_document(document_id));
create policy "owners revoke sharing" on public.document_access for delete to authenticated using (public.owns_document(document_id));
insert into storage.buckets (id, name, public) values ('document-attachments', 'document-attachments', false) on conflict (id) do nothing;
create policy "document members upload attachments" on storage.objects for insert to authenticated with check (bucket_id = 'document-attachments' and (public.owns_document((storage.foldername(name))[1]::uuid) or public.can_access_document((storage.foldername(name))[1]::uuid)));
create policy "document members read attachments" on storage.objects for select to authenticated using (bucket_id = 'document-attachments' and (public.owns_document((storage.foldername(name))[1]::uuid) or public.can_access_document((storage.foldername(name))[1]::uuid)));